lore-settings:
  unowned:
    - ''
    - '&cYou don''t own {item-display}'
    - ''
    - '&7Price for {item-display} &7is &e{price}'
    - '&7Click to purchase {item-display}'
    - '&7Shift-Left-Click to preview'
    - ''
  owned:
    - ''
    - '&aYou already own {item-display}'
    - ''
    - '&7Click to equip your item with {item-display}'
    - '&7Shift-Left-Click to preview'
    - ''

GUI:
  # Button to move to the next page in the GUI for more armor slots.
  next-page:
    material: PLAYER_HEAD
    model: 0
    display-name: "&aNext Page"
    lore:
      - "&7View additional armor slots on the next page."
    base64: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2M2MDJkYmE5Zjk3MDFhZTAwMzllNzQ4MWNlYmY2MWM1OGZlOGQzOWQyOWM5MjdiNDg4YmVlNDIyZDlhNjJkNCJ9fX0="

  # Button to go back to the previous page.
  previous-page:
    material: PLAYER_HEAD
    model: 0
    display-name: "&aPrevious Page"
    lore:
      - "&7Go back to the previous page for other armor slots."
    base64: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjEzNGJhMjQxZjg3M2Q1ZWY0YzUyNmViMjkxYjVjMTZkNTA3ZDVhMGM2ZjFhMmU2NTAzZWM1OWIzNjNhMzY3NSJ9fX0="

  close-menu:
    material: PLAYER_HEAD
    model: 0
    display-name: "&cClose Menu"
    lore:
      - "&7Click to close the menu."
    base64: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWZkMjQwMDAwMmFkOWZiYmJkMDA2Njk0MWViNWIxYTM4NGFiOWIwZTQ4YTE3OGVlOTZlNGQxMjlhNTIwODY1NCJ9fX0="

  item-filter:
    material: GRAY_STAINED_GLASS_PANE
    model: 0
    display-name: " "
    lore: []

# Configuration for the metamorph command functionality in-game.
# Will add options for sub commands shortly. but at the moment they're a bit restricted.
Command:
  # The primary name for the metamorph command used in-game.
  # Example: Setting this to 'metamorph' means players will use /metamorph in-game.
  name: 'metamorph'  # This defines the command players will type.

  # A brief description of the /metamorph command for help menus or command listings.
  description: 'Explore the server resource pack in style!'  # Describe the command's purpose.

  # Instructions on how to properly use the command.
  # Provides users with an example usage format.
  usage: '/metamorph <sub command | optional>'  # Shows how to execute the command.

  # A list of aliases for the /metamorph command.
  # Players can use these shortcuts to invoke the command.
  # To disable aliases, simply set this to 'aliases: []'.
  aliases:
    - 'mm'   # Allow players to use /mm as a shortcut for /metamorph.
    - 'mmo'    # Allow players to use /mmo as a shortcut for /metamorph.

  permission: 'mm.use' #This permission simply gives you the permission to use the /metamorph command.

#Enable update checker, to get notified if you're using an outdated version? (true - false)
update-checker: true