lore-settings:
  unowned:
    - ''
    - '&cYou don''t own {item-display}'
    - ''
    - '&7Price for {item-display} &7is &e{price}'
    - '&7Click to purchase {item-display}'
    - '&7Middle Mouse Click to preview'
    - ''
  owned:
    - ''
    - '&aYou already own {item-display}'
    - ''
    - '&7Click to equip your item with {item-display}'
    - '&7Middle Mouse Click to preview'
    - ''

# Configuration for the metamorph command functionality in-game.
Command:
  # The primary name for the metamorph command used in-game.
  # Example: Setting this to 'metamorph' means players will use /metamorph in-game.
  name: 'metamorph'  # This defines the command players will type.

  # A brief description of the /metamorph command for help menus or command listings.
  description: 'Explore the server resource pack in style!'  # Describe the command's purpose.

  # Instructions on how to properly use the command.
  # Provides users with an example usage format.
  usage: '/metamorph <sub command | optional>'  # Shows how to execute the command.

  # A list of aliases for the /metamorph command.
  # Players can use these shortcuts to invoke the command.
  # To disable aliases, simply set this to 'aliases: []'.
  aliases:
    - 'mm'   # Allow players to use /mm as a shortcut for /metamorph.
    - 'mmo'    # Allow players to use /mmo as a shortcut for /metamorph.